// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WorldSession.proto

#ifndef PROTOBUF_WorldSession_2eproto__INCLUDED
#define PROTOBUF_WorldSession_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace TestSession {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_WorldSession_2eproto();
void protobuf_AssignDesc_WorldSession_2eproto();
void protobuf_ShutdownFile_WorldSession_2eproto();

class TestMsg;

// ===================================================================

class TestMsg : public ::google::protobuf::Message {
 public:
  TestMsg();
  virtual ~TestMsg();

  TestMsg(const TestMsg& from);

  inline TestMsg& operator=(const TestMsg& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TestMsg& default_instance();

  void Swap(TestMsg* other);

  // implements Message ----------------------------------------------

  TestMsg* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const TestMsg& from);
  void MergeFrom(const TestMsg& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 msgid = 1 [default = 1];
  inline bool has_msgid() const;
  inline void clear_msgid();
  static const int kMsgidFieldNumber = 1;
  inline ::google::protobuf::uint32 msgid() const;
  inline void set_msgid(::google::protobuf::uint32 value);

  // optional string user_name = 2;
  inline bool has_user_name() const;
  inline void clear_user_name();
  static const int kUserNameFieldNumber = 2;
  inline const ::std::string& user_name() const;
  inline void set_user_name(const ::std::string& value);
  inline void set_user_name(const char* value);
  inline void set_user_name(const char* value, size_t size);
  inline ::std::string* mutable_user_name();
  inline ::std::string* release_user_name();
  inline void set_allocated_user_name(::std::string* user_name);

  // @@protoc_insertion_point(class_scope:TestSession.TestMsg)
 private:
  inline void set_has_msgid();
  inline void clear_has_msgid();
  inline void set_has_user_name();
  inline void clear_has_user_name();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* user_name_;
  ::google::protobuf::uint32 msgid_;
  friend void  protobuf_AddDesc_WorldSession_2eproto();
  friend void protobuf_AssignDesc_WorldSession_2eproto();
  friend void protobuf_ShutdownFile_WorldSession_2eproto();

  void InitAsDefaultInstance();
  static TestMsg* default_instance_;
};
// ===================================================================


// ===================================================================

// TestMsg

// optional uint32 msgid = 1 [default = 1];
inline bool TestMsg::has_msgid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void TestMsg::set_has_msgid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void TestMsg::clear_has_msgid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void TestMsg::clear_msgid() {
  msgid_ = 1u;
  clear_has_msgid();
}
inline ::google::protobuf::uint32 TestMsg::msgid() const {
  // @@protoc_insertion_point(field_get:TestSession.TestMsg.msgid)
  return msgid_;
}
inline void TestMsg::set_msgid(::google::protobuf::uint32 value) {
  set_has_msgid();
  msgid_ = value;
  // @@protoc_insertion_point(field_set:TestSession.TestMsg.msgid)
}

// optional string user_name = 2;
inline bool TestMsg::has_user_name() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void TestMsg::set_has_user_name() {
  _has_bits_[0] |= 0x00000002u;
}
inline void TestMsg::clear_has_user_name() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void TestMsg::clear_user_name() {
  if (user_name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    user_name_->clear();
  }
  clear_has_user_name();
}
inline const ::std::string& TestMsg::user_name() const {
  // @@protoc_insertion_point(field_get:TestSession.TestMsg.user_name)
  return *user_name_;
}
inline void TestMsg::set_user_name(const ::std::string& value) {
  set_has_user_name();
  if (user_name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    user_name_ = new ::std::string;
  }
  user_name_->assign(value);
  // @@protoc_insertion_point(field_set:TestSession.TestMsg.user_name)
}
inline void TestMsg::set_user_name(const char* value) {
  set_has_user_name();
  if (user_name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    user_name_ = new ::std::string;
  }
  user_name_->assign(value);
  // @@protoc_insertion_point(field_set_char:TestSession.TestMsg.user_name)
}
inline void TestMsg::set_user_name(const char* value, size_t size) {
  set_has_user_name();
  if (user_name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    user_name_ = new ::std::string;
  }
  user_name_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:TestSession.TestMsg.user_name)
}
inline ::std::string* TestMsg::mutable_user_name() {
  set_has_user_name();
  if (user_name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    user_name_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:TestSession.TestMsg.user_name)
  return user_name_;
}
inline ::std::string* TestMsg::release_user_name() {
  clear_has_user_name();
  if (user_name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = user_name_;
    user_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void TestMsg::set_allocated_user_name(::std::string* user_name) {
  if (user_name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete user_name_;
  }
  if (user_name) {
    set_has_user_name();
    user_name_ = user_name;
  } else {
    clear_has_user_name();
    user_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:TestSession.TestMsg.user_name)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace TestSession

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_WorldSession_2eproto__INCLUDED
